Update run.-script.yml

diff --git a/.github/workflows/run.-script.yml b/.github/workflows/run.-script.yml
--- a/.github/workflows/run.-script.yml
+++ b/.github/workflows/run.-script.yml
@@ -21,7 +21,7 @@ on:
 jobs:
   run-script:
     name: Run script
-    runs-on: ubuntu-latest # [ self-hosted, build-runner-new ]
+    runs-on: ubuntu-latest
     environment: ${{ github.event.inputs.environment }}
 
     steps:
@@ -58,34 +58,34 @@ jobs:
           fi
 
 
-#          # NOW FOR SOME VALIDATION THAT THE TS FILE
-#          # 1 - has a 'run' function
-#          # 2 - that 'run' returns a 'ScriptRunResult' type
-#          # 3 - that 'run' is executed
-#          TS_SCRIPT_NAME="${SCRIPT_NAME%.js}.ts"
-#          TS_BASE_PATH="./src/scripts"
-#          TS_SCRIPT_PATH="$TS_BASE_PATH/$TS_SCRIPT_NAME"
-#          if [[ ! -f "$TS_SCRIPT_PATH" ]]; then
-#            echo "Error: TypeScript script '$TS_SCRIPT_PATH' does not exist."
-#            exit 1
-#          fi
-#          # Check if the script contains 'export function run' or 'export const run'
-#          # Use grep to check for arrow functions, regular functions, and default exports
-#          if ! grep -qE "export\s+(const\s+run\s*=|function\s+run\s*\()" "$TS_SCRIPT_PATH" && ! grep -q "export\s+default\s+run\s*\(" "$SCRIPT_PATH"; then
-#            echo "Error: The script must export a 'run' function."
-#            exit 1
-#          fi
-#          # Validate return type of run function
-#          # Use grep to ensure the script's run function returns a ScriptRunResult
-#          if ! grep -qE "export\s+(const\s+run\s*=|function\s+run\s*\()[^\)]*\)\s*:\s*(ScriptRunResult)" "$TS_SCRIPT_PATH" && ! grep -qE "export\s+default\s+run\s*\([^\)]*\)\s*:\s*(ScriptRunResult)" "$SCRIPT_PATH"; then
-#            echo "Error: The 'run' function must return a type of 'ScriptRunResult'."
-#            exit 1
-#          fi
-#          # Check if the run function is executed
-#          if ! grep -qE "\brun\s*\(" "$TS_SCRIPT_PATH"; then
-#          echo "Error: The 'run' function must be executed (called) in the script."
-#          exit 1
-#          fi
+          # NOW FOR SOME VALIDATION THAT THE TS FILE
+          # 1 - has a 'run' function
+          # 2 - that 'run' returns a 'ScriptRunResult' type
+          # 3 - that 'run' is executed
+          TS_SCRIPT_NAME="${SCRIPT_NAME%.js}.ts"
+          TS_BASE_PATH="./src/scripts"
+          TS_SCRIPT_PATH="$TS_BASE_PATH/$TS_SCRIPT_NAME"
+          if [[ ! -f "$TS_SCRIPT_PATH" ]]; then
+            echo "Error: TypeScript script '$TS_SCRIPT_PATH' does not exist."
+            exit 1
+          fi
+          # Check if the script contains 'export function run' or 'export const run'
+          # Use grep to check for arrow functions, regular functions, and default exports
+          if ! grep -qE "export\s+(const\s+run\s*=|function\s+run\s*\()" "$TS_SCRIPT_PATH" && ! grep -q "export\s+default\s+run\s*\(" "$SCRIPT_PATH"; then
+            echo "Error: The script must export a 'run' function."
+            exit 1
+          fi
+          # Validate return type of run function
+          # Use grep to ensure the script's run function returns a ScriptRunResult
+          if ! grep -qE "export\s+(const\s+run\s*=|function\s+run\s*\()[^\)]*\)\s*:\s*(ScriptRunResult)" "$TS_SCRIPT_PATH" && ! grep -qE "export\s+default\s+run\s*\([^\)]*\)\s*:\s*(ScriptRunResult)" "$SCRIPT_PATH"; then
+            echo "Error: The 'run' function must return a type of 'ScriptRunResult'."
+            exit 1
+          fi
+          # Check if the run function is executed
+          if ! grep -qE "\brun\s*\(" "$TS_SCRIPT_PATH"; then
+          echo "Error: The 'run' function must be executed (called) in the script."
+          exit 1
+          fi
 
 
           # Save for later steps
